### ISSUE TITLE
IS_ACUtil library

### ISSUE THREAD

**Issue by dasGringuen** [Jurredr/ACRL#5]
Hi,

Great work!

I see you're using the AC-Util library to send commands 68 and 69. I have a few questions: 

1. Where did you get the IS_ACUtil.pyc file?
2. What do these numbers represent?

Thanks, and keep up the great work!

Adrian

**Comment by Jurredr** [comment]
Hi Adrian,

Apologies for the late response. I only just now stumbled upon this comment!
I unfortunately never found the answer to these questions myself. I think I found this util file in the source of some plugin someone created on an Assetto Corsa forum. It was quite old and I didn't find the time to contact the creator for more info.

I assume these numbers represent some internal binary commands, however which number maps to which command, I was not able to find myself either.

Sorry for the useless answer, but thanks for your interest!
